// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use the direct connection (port 5432) for migrations/db:push.
    // The pooled DATABASE_URL (port 6543) is used at runtime via PrismaPg adapter in lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
